Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the
dataset information to understand its structure.

In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv("retail_dataset .csv.")

# Firest 5 Rows
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [10]:
#information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing
values present in the dataset

In [12]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.

In [14]:
df["Quantity"].fillna(df["Quantity"].mean(),inplace=True)
df["Price"].fillna(df["Price"].mean(),inplace=True)

C:\Users\-DELL\AppData\Local\Temp\ipykernel_15616\1846713954.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Quantity"].fillna(df["Quantity"].mean(),inplace=True)
C:\Users\-DELL\AppData\Local\Temp\ipykernel_15616\1846713954.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].mean(),inplace=True)

Q4. Remove all rows where the Product Category or Region column contains missing values.

In [19]:
df.dropna(subset=["Product Category","Region"])

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

Q5. Create a new column called Revenue using NumPy, where:Revenue = Quantity × Price
Display the updated dataset with the new column.

In [20]:
df["Revenu"]= df["Quantity"] * df["Price"]
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenu
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.

In [26]:
total_revenu = np.sum(df["Revenu"])
print("Total Revenu",total_revenu)

Total Revenu 491834.8711063373

Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.

In [34]:
category_revenu =df.groupby("Product Category")["Revenu"].sum()
print(category_revenu)

Product Category
Beauty          28691.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            60512.090226
Name: Revenu, dtype: float64

Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the
highest revenue and the bottom 3 categories with the lowest revenue.

In [39]:
# Top 3 
category_revenu.nsmallest(3)

Product Category
Groceries    11978.000000
Beauty       28691.000000
Books        29597.938776
Name: Revenu, dtype: float64

In [40]:
# Bottom 3 
category_revenu.nsmallest(3)

Product Category
Groceries    11978.000000
Beauty       28691.000000
Books        29597.938776
Name: Revenu, dtype: float64

Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the
region with the highest revenue and the region with the lowest revenue

In [42]:
reginol_revenu = df.groupby("Region")["Revenu"].sum()
reginol_revenu

Region
East     135184.044039
North    162989.353383
South    104855.736842
West      81197.526316
Name: Revenu, dtype: float64

In [44]:
# Region of highest revenu 
reginol_revenu.nlargest(1)

Region
North    162989.353383
Name: Revenu, dtype: float64

In [45]:
# Rgion of lowest revenu 
reginol_revenu.nsmallest(1)

Region
West    81197.526316
Name: Revenu, dtype: float64

Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the
total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column
using NumPy.